apiVersion: v1
kind: Service
metadata:
  name: react-app-svc
  labels:
    app: react-app-svc
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: react-app-port
      targetPort: http-port
  selector:
    app: react-app
