name: ts-app pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - closed
      - reopened
jobs:
  run-frontend-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run unit tests
        working-directory: frontend
        run: npm install && npm run test
  run-backend-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run unit tests
        working-directory: backend
        run: bun install && bun run test
